### PR TITLE
ask for year first in date picker

### PR DESCRIPTION
**Pull request by RomainL972**
I saw many comments saying that it's too hard to scroll month by month. I found a way to ask for the year before the day and the month, I believe people will find this easier.

### CODE REVIEW

**Comment by tananaev** [comment]
Can you provide a screenshot/gif to see what it looks like now?

**Comment by RomainL972** [comment]
https://transfer.sh/5xkO1/20-06-17-19-02-35.mp4

**Comment by tananaev** [comment]
This is awesome, thanks for the PR. Merged.

Is there a way to set an earlier year as a default for birth date?

**Comment by RomainL972** [comment]
I don't know if it's possible, but the problem would be that if a previous date is saved, it would reset it.

**Comment by tananaev** [comment]
Default is current year, right? So we can probably check for that.

**Pull request merged**
