### PR TITLE
add metadata for f-droid integration

### PR DESCRIPTION
**Pull request by RomainL972**
Hi,

This pull request contains metadata files needed to add passport-reader to the F-Droid repository.

### CODE REVIEW

**Comment by tananaev** [comment]
I'm not sure this belongs in the repository. Why not submit this information directly to the F-Droid?

**Comment by RomainL972** [comment]
The reviewers of the merge request for adding passport reader to f-droid asked for this information to be added to this repository if possible. It lets us change the information that appears on the f-droid page without creating a merge request on the fdroiddata gitlab every time. If you want, here is the merge request : https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6583
Also, is it possible to add a new tag if this pull request is merged so that the f-droid bot can automatically scan the metadata using the new tag ?

**Comment by IzzySoft** [comment]
@tananaev this should be added to your repository for multiple reasons, e.g.: 

* **you** can keep summary & description etc. up-to-date without requiring merge requests for each change
* screenshots cannot be added to the F-Droid git repo anymore; with more than 3k apps it otherwise would get unmaintainable

Besides, Fastlane is a de-facto standard and can be used with other places (like Google Play) as well.

**Comment by IzzySoft** [comment]
@tananaev any news on this? We'd really like to add your app, but that requires this PR being merged first and after that a new release being made here (with "Fastlane inside").

**Pull request closed without merging**
