### PR TITLE
Fix pace

### PR DESCRIPTION
**Pull request by RomainL972**
The changes from https://github.com/tananaev/passport-reader/pull/24 but with the import that allows the build to succeed

### CODE REVIEW

**Comment by tananaev** [comment]
@RomainL972 I get reports that this actually breaks decoding for some passports. Reverting it fixes the issue.

**Comment by RomainL972** [comment]
I'll try to investigate, is there any information about which passports don't work?

**Comment by tananaev** [comment]
Austrian passport, but another one worked. Not sure. I also noticed that my Russian passport stopped working, even though it worked before. Not sure if it's related.

**Comment by RomainL972** [comment]
Does it always happen, or only sometimes? It might just be a random reading error.

-------- Original Message --------

**Comment by tananaev** [comment]
For me it happens all the time, but again, I'm not sure it's the same issue. For the person who reported the issue with Austrian passport, I'm not sure. I asked him to reply here, but he hasn't yet.

**Pull request merged**
